Add checks for n-ts dependencies

diff --git a/bash/bin/n-ts b/bash/bin/n-ts
--- a/bash/bin/n-ts
+++ b/bash/bin/n-ts
@@ -5,6 +5,16 @@ set -e
 echo "newts installs a new typescript project in your current directory"
 echo ""
 
+if ! [ -x "$(command -v git)" ]; then
+  echo 'Error: git is not installed.' >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v npm)" ]; then
+  echo 'Error: npm is not installed.' >&2
+  exit 1
+fi
+
 project_name=$1
 project_dir="$(pwd)/$project_name"
 
